version: '3.8'

services:
  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile.simple
    container_name: robot-scheduler-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: tail -f /dev/null  # Keep container running
    depends_on:
      - redis
      - postgres
    stdin_open: true
    tty: true
