version: '3.8'

services:
  research:
    build:
      context: .
      dockerfile: docker/Dockerfile.research
    container_name: scheduling-research
    volumes:
      - ./research-code:/app/research-code
      - ./results:/app/results
      - ./test_cases:/app/test_cases
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app:/app/research-code
      - PYTHONUNBUFFERED=1
    ports:
      - "8888:8888"  # Jupyter Lab
    entrypoint: ["/entrypoint.sh"]
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    stdin_open: true
    tty: true